{
 "title": "First dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Docker Containers | Telegraf", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cron Job Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "SELECT COUNT(\"command\") FROM \"cron_error_log\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Disk Usage - Docker Telegraf",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"usage_guest\") FROM \"cpu\" WHERE (\"host\" = 'docker-telegraf' AND \"customer\" = 'testcustomer' AND \"os\" = 'Linux' AND \"environment\" = 'Dev') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "docker-telegraf" },
      { "condition": "AND", "key": "customer", "operator": "=", "value": "testcustomer" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "Linux" },
      { "condition": "AND", "key": "environment", "operator": "=", "value": "Dev" }
     ]
    }
   ]
  },
  {
   "title": "Nginx Status - Docker Telegraf",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "port::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nginx",
     "query": "SELECT count(\"active\") FROM \"nginx\" WHERE (\"host\"::tag = 'docker-telegraf' AND \"customer\"::tag = 'testcustomer' AND \"os\"::tag = 'Linux' AND \"port\"::tag = '80') AND $timeFilter GROUP BY time(1m), \"port\"::tag fill(null)",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "docker-telegraf" },
      { "condition": "AND", "key": "customer::tag", "operator": "=", "value": "testcustomer" },
      { "condition": "AND", "key": "os::tag", "operator": "=", "value": "Linux" },
      { "condition": "AND", "key": "port::tag", "operator": "=", "value": "80" }
     ]
    }
   ]
  },
  {
   "title": "Nginx Active Connections - Docker Telegraf",
   "type": "stat",
   "description": "Nginx - Active Connections",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "nginx",
     "query": "SELECT sum(\"active\") \nFROM \"nginx\" \nWHERE \"host\" = 'docker-telegraf' \n  AND \"customer\" = 'testcustomer' \n  AND \"os\" = 'Linux' \n  AND \"port\" = '80' \n  AND $timeFilter \nGROUP BY time(5s) fill(null)",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "docker-telegraf" },
      { "condition": "AND", "key": "customer::tag", "operator": "=", "value": "testcustomer" },
      { "condition": "AND", "key": "os::tag", "operator": "=", "value": "Linux" },
      { "condition": "AND", "key": "port::tag", "operator": "=", "value": "80" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage - Docker Telegraf Second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"usage_guest\") FROM \"cpu\" WHERE (\"host\" = 'docker-telegraf' AND \"customer\" = 'testcustomer' AND \"os\" = 'Linux' AND \"environment\" = 'Dev') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "docker-telegraf-second" },
      { "condition": "AND", "key": "customer", "operator": "=", "value": "testcustomer" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "Linux" },
      { "condition": "AND", "key": "environment", "operator": "=", "value": "Dev" }
     ]
    }
   ]
  },
  {
   "title": "Nginx Requests - Docker Telegraf",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "nginx",
     "query": "SELECT sum(\"requests\") \nFROM \"nginx\" \nWHERE \"host\" = 'docker-telegraf' \n  AND \"customer\" = 'testcustomer' \n  AND \"os\" = 'Linux' \n  AND \"port\" = '80' \n  AND $timeFilter \nGROUP BY time(5s) fill(null)",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "docker-telegraf" },
      { "condition": "AND", "key": "customer::tag", "operator": "=", "value": "testcustomer" },
      { "condition": "AND", "key": "os::tag", "operator": "=", "value": "Linux" },
      { "condition": "AND", "key": "port::tag", "operator": "=", "value": "80" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage - Docker Telegraf",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_guest\") FROM \"cpu\" WHERE (\"host\" = 'docker-telegraf' AND \"customer\" = 'testcustomer' AND \"os\" = 'Linux' AND \"environment\" = 'Dev') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "usage_guest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "docker-telegraf" },
      { "condition": "AND", "key": "customer", "operator": "=", "value": "testcustomer" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "Linux" },
      { "condition": "AND", "key": "environment", "operator": "=", "value": "Dev" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage - Docker Telegraf",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_guest\") FROM \"cpu\" WHERE (\"host\" = 'docker-telegraf' AND \"customer\" = 'testcustomer' AND \"os\" = 'Linux' AND \"environment\" = 'Dev') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "usage_guest" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "docker-telegraf" },
      { "condition": "AND", "key": "customer", "operator": "=", "value": "testcustomer" },
      { "condition": "AND", "key": "os", "operator": "=", "value": "Linux" },
      { "condition": "AND", "key": "environment", "operator": "=", "value": "Dev" }
     ]
    }
   ]
  }
 ]
}